(function(global){
  'use strict';
  function id(){return global.crypto&&crypto.randomUUID?crypto.randomUUID():'r-'+Date.now()+'-'+Math.random().toString(16).slice(2)}
  function endpoint(){const cfg=global.KRUA_FLOW_CONFIG||{},staging=new URLSearchParams(location.search).get('staging')==='1',value=staging?(cfg.STAGING_API_URL||''):cfg.API_URL;if(!/^https:\/\/script\.google\.com\/macros\/s\/.+\/exec/.test(String(value||'')))throw new Error('Backend URL ไม่ถูกต้อง');return String(value).split('?')[0]}
  function Client(options){this.url=(options&&options.url)||endpoint();this.timeout=(options&&options.timeout)||30000;this.pending={};this.sink=null;this.onMessage=this.onMessage.bind(this);global.addEventListener('message',this.onMessage)}
  Client.prototype.ensureSink=function(){if(this.sink)return;const f=document.createElement('iframe');f.name='kfApiSinkV2';f.id='kfApiSinkV2';f.hidden=true;document.body.appendChild(f);this.sink=f};
  Client.prototype.finish=function(requestId,ok,value){const p=this.pending[requestId];if(!p)return;clearTimeout(p.timeout);delete this.pending[requestId];ok?p.resolve(value):p.reject(value)};
  Client.prototype.onMessage=function(event){if(!this.sink||event.source!==this.sink.contentWindow)return;const m=event.data||{};if(m.type!=='KruaFlowApiResult'||!this.pending[m.requestId])return;const r=m.result||{};this.finish(m.requestId,Boolean(r.ok),r.ok?(r.data||{}):new Error(r.error||'ทำรายการไม่สำเร็จ'))};
  Client.prototype.poll=function(requestId,attempt){const self=this;if(!self.pending[requestId])return;if(attempt>16){self.finish(requestId,false,new Error('Backend ไม่ตอบสนอง'));return}const callback='__kfv2_'+requestId.replace(/[^A-Za-z0-9_]/g,'_')+'_'+attempt,script=document.createElement('script');let done=false;function clean(){if(done)return;done=true;try{delete global[callback]}catch(e){}script.remove()}global[callback]=function(r){clean();if(!r||!r.ready){setTimeout(()=>self.poll(requestId,attempt+1),700);return}self.finish(requestId,Boolean(r.ok),r.ok?(r.data||{}):new Error(r.error||'ทำรายการไม่สำเร็จ'))};script.onerror=function(){clean();setTimeout(()=>self.poll(requestId,attempt+1),900)};script.src=self.url+'?api=status&requestId='+encodeURIComponent(requestId)+'&callback='+encodeURIComponent(callback)+'&_='+Date.now();document.head.appendChild(script);setTimeout(function(){if(!done){clean();setTimeout(()=>self.poll(requestId,attempt+1),900)}},3000)};
  Client.prototype.call=function(payload){if(global.KRUA_FLOW_MOCK&&global.KRUA_FLOW_MOCK.enabled)return Promise.resolve(global.KRUA_FLOW_MOCK.handle(payload));this.ensureSink();const self=this,requestId=id();payload=Object.assign({},payload,{requestId:requestId,clientOrigin:location.origin});return new Promise(function(resolve,reject){const form=document.createElement('form'),input=document.createElement('input');form.method='POST';form.action=self.url;form.target=self.sink.name;form.hidden=true;input.name='payload';input.value=JSON.stringify(payload);form.appendChild(input);document.body.appendChild(form);self.pending[requestId]={resolve:resolve,reject:reject,timeout:setTimeout(()=>self.finish(requestId,false,new Error('Backend ตอบช้าเกินไป')),self.timeout)};try{form.submit()}catch(e){self.finish(requestId,false,e)}setTimeout(()=>form.remove(),2500);setTimeout(()=>self.poll(requestId,0),450)})};
  global.KruaFlowApi={Client:Client,endpoint:endpoint};
})(window);
