// Configurable performance metrics. Raw source records remain immutable.

function wf2AdminGetKpiDefinitions_(payload){requireAdmin_(String(payload.adminToken||''));return{definitions:wf2Rows_('KPI_Definitions').map(wf2ClientRow_),targets:wf2Rows_('KPI_Targets').map(wf2ClientRow_)}}

function wf2AdminSaveKpiDefinition_(payload){requireAdmin_(String(payload.adminToken||''));const data=payload.definition||{},key=String(data.key||'').trim().toLowerCase();if(!/^[a-z][a-z0-9_]{2,60}$/.test(key))throw new Error('KPI key ไม่ถูกต้อง');const source=String(data.source||''),supported=['attendance_rate','on_time_rate','absence_count','activity_submission_rate','activity_completion_rate','activity_on_time_rate','incident_count','training_completion_rate','supervisor_evaluation'];if(supported.indexOf(key)<0)throw new Error('KPI source calculator ยังไม่รองรับ key นี้');const existing=wf2Rows_('KPI_Definitions').find(r=>String(r['KPI Key'])===key),record={'KPI Key':key,'Name':String(data.name||key),'Description':String(data.description||''),'Source':source,'Formula Type':String(data.formulaType||'RATIO'),'Formula':String(data.formula||''),'Numerator':String(data.numerator||''),'Denominator':String(data.denominator||''),'Unit':String(data.unit||'PERCENT'),'Period':String(data.period||'CUSTOM'),'Dimension':String(data.dimension||'EMPLOYEE'),'Target':Number(data.target)||0,'Direction':String(data.direction||'HIGHER_IS_BETTER'),'Weight':Number(data.weight)||0,'Applicable Position':String(data.applicablePosition||''),'Applicable Department':String(data.applicableDepartment||''),'Applicable Branch':String(data.applicableBranch||''),'Lifecycle Stage':String(data.lifecycleStage||''),'Owner':String(data.owner||'HR'),'Data Quality Status':'CONFIGURED','Active':data.active!==false,'Updated At':new Date()};if(existing)wf2UpdateRow_('KPI_Definitions',existing._row,record);else{record['Created At']=new Date();wf2Append_('KPI_Definitions',record)}return{ok:true,key:key}}

function wf2PerformanceSources_(employee,startKey,endKey){
  const ss=SpreadsheetApp.openById(SPREADSHEET_ID),versions=new Set(scheduleVersionRowsV7_().filter(v=>v.status==='PUBLISHED').map(v=>v.versionId)),scheduleSh=ss.getSheetByName(WORK_SCHEDULES_SHEET),scheduled=[];
  if(scheduleSh&&scheduleSh.getLastRow()>=2)scheduleSh.getRange(2,1,scheduleSh.getLastRow()-1,17).getValues().forEach(r=>{const date=attendanceDateKey_(r[3]);if(versions.has(String(r[1]))&&String(r[4])===employee.id&&date>=startKey&&date<=endKey&&['WORK','SCHEDULED',''].indexOf(String(r[9]||'').toUpperCase())>=0)scheduled.push({date:date,shiftCode:String(r[8]||'')})});
  const leaveDates=new Set();approvedLeavesForRange_(ss,employee.id,startKey,endKey).forEach(l=>{let d=parseIsoDate_(l.startDate),end=parseIsoDate_(l.endDate);while(d&&end&&d<=end){leaveDates.add(Utilities.formatDate(d,TZ,'yyyy-MM-dd'));d=new Date(d.getTime()+86400000)}});for(let i=scheduled.length-1;i>=0;i--)if(leaveDates.has(scheduled[i].date))scheduled.splice(i,1);
  const events=attendanceEventsForPayroll_(ss,employee.id,startKey,endKey),firstIn={};events.forEach(e=>{const kind=actionKindServer_(e.action),date=Utilities.formatDate(e.timestamp,TZ,'yyyy-MM-dd');if(kind==='IN'&&(!firstIn[date]||e.timestamp<firstIn[date]))firstIn[date]=e.timestamp});
  let present=0,onTime=0,validCheckIns=0;scheduled.forEach(s=>{const check=firstIn[s.date];if(!check)return;present++;validCheckIns++;try{const window=shiftWindowV7_(s.date,s.shiftCode),grace=Number(window.shift.lateGraceMinutes)||0;if(check.getTime()<=window.start.getTime()+grace*60000)onTime++}catch(e){}});
  const reports=wf2Rows_('Activity_Reports').filter(r=>String(r['Employee ID'])===employee.id&&attendanceDateKey_(r['Date'])>=startKey&&attendanceDateKey_(r['Date'])<=endKey),reportIds=new Set(reports.map(r=>String(r['Activity Report ID']))),items=wf2Rows_('Activity_Items').filter(r=>reportIds.has(String(r['Report ID']))),submitted=reports.filter(r=>/^SUBMITTED/.test(String(r['Status']))).length,done=items.filter(r=>String(r['Status'])==='DONE').length,onTimeDone=items.filter(r=>String(r['Status'])==='DONE'&&(!r['Due At']||new Date(r['Completed At'])<=new Date(r['Due At']))).length;
  const incidents=wf2Rows_('Employee_Incidents').filter(r=>String(r['Employee ID'])===employee.id&&attendanceDateKey_(r['Date'])>=startKey&&attendanceDateKey_(r['Date'])<=endKey).length,catalog=wf2Rows_('Training_Catalog').filter(r=>r['Active']!==false&&(!String(r['Required Position'])||String(r['Required Position'])===employee.position)),training=wf2Rows_('Employee_Training').filter(r=>String(r['Employee ID'])===employee.id&&catalog.some(c=>String(c['Training ID'])===String(r['Training ID']))),completedTraining=new Set(training.filter(r=>String(r['Status'])==='COMPLETED').map(r=>String(r['Training ID']))).size,reviews=wf2Rows_('Performance_Reviews').filter(r=>String(r['Employee ID'])===employee.id&&attendanceDateKey_(r['Period Start'])<=endKey&&attendanceDateKey_(r['Period End'])>=startKey&&String(r['Status'])==='SUBMITTED'),supervisor=reviews.length?reviews.reduce((s,r)=>s+(Number(r['Numeric Rating'])||0),0)/reviews.length:null;
  return {attendance_rate:wf2Metric_('attendance_rate','Schedules + Attendance',present,scheduled.length,'present scheduled shifts / required scheduled shifts','PERCENT'),on_time_rate:wf2Metric_('on_time_rate','Schedules + Attendance',onTime,validCheckIns,'on-time check-ins / valid required check-ins','PERCENT'),absence_count:{key:'absence_count',source:'Schedules + Attendance',numerator:Math.max(0,scheduled.length-present),denominator:null,value:Math.max(0,scheduled.length-present),formula:'required scheduled shifts - present scheduled shifts',unit:'COUNT',dataQualityStatus:'OK'},activity_submission_rate:wf2Metric_('activity_submission_rate','Activity_Reports',submitted,reports.length,'submitted reports / required reports','PERCENT'),activity_completion_rate:wf2Metric_('activity_completion_rate','Activity_Items',done,items.length,'DONE items / assigned items','PERCENT'),activity_on_time_rate:wf2Metric_('activity_on_time_rate','Activity_Items',onTimeDone,done,'DONE by dueAt / DONE items','PERCENT'),incident_count:{key:'incident_count',source:'Employee_Incidents',numerator:incidents,denominator:null,value:incidents,formula:'incident records in period',unit:'COUNT',dataQualityStatus:'OK'},training_completion_rate:wf2Metric_('training_completion_rate','Training_Catalog + Employee_Training',completedTraining,catalog.length,'completed required training / required training','PERCENT'),supervisor_evaluation:{key:'supervisor_evaluation',source:'Performance_Reviews',numerator:supervisor,denominator:null,value:supervisor,formula:'average submitted supervisor numeric rating',unit:'RATING',dataQualityStatus:supervisor==null?'NO_DATA':'OK'}};
}

function wf2Metric_(key,source,numerator,denominator,formula,unit){return{key:key,source:source,numerator:numerator,denominator:denominator,value:denominator>0?wf2Ratio_(numerator,denominator):null,formula:formula,unit:unit,dataQualityStatus:denominator>0?'OK':'NO_DENOMINATOR'}}

function wf2ApplicableKpis_(employee,lifecycle){return wf2Rows_('KPI_Definitions').filter(r=>r['Active']!==false&&(!String(r['Applicable Position'])||String(r['Applicable Position'])===employee.position)&&(!String(r['Applicable Department'])||String(r['Applicable Department'])===employee.department)&&(!String(r['Applicable Branch'])||String(r['Applicable Branch'])===employee.branch)&&(!String(r['Lifecycle Stage'])||String(r['Lifecycle Stage'])===lifecycle))}

function wf2ResolveKpiConfig_(definition,employee,lifecycle,startKey,endKey){const key=String(definition['KPI Key']),matches=wf2Rows_('KPI_Targets').filter(r=>r['Active']!==false&&String(r['KPI Key'])===key&&(!String(r['Position Code'])||String(r['Position Code'])===employee.position)&&(!String(r['Department Code'])||String(r['Department Code'])===employee.department)&&(!String(r['Branch Code'])||String(r['Branch Code'])===employee.branch)&&(!String(r['Lifecycle Stage'])||String(r['Lifecycle Stage'])===lifecycle)&&(!r['Effective Start']||attendanceDateKey_(r['Effective Start'])<=endKey)&&(!r['Effective End']||attendanceDateKey_(r['Effective End'])>=startKey));matches.sort((a,b)=>{const score=x=>(String(x['Branch Code'])?4:0)+(String(x['Department Code'])?2:0)+(String(x['Position Code'])?1:0);return score(b)-score(a)});const target=matches[0];return{target:target?Number(target['Target']):Number(definition['Target']),weight:target?Number(target['Weight']):Number(definition['Weight']),direction:String(definition['Direction']||'HIGHER_IS_BETTER')}}

function wf2ScoreMetric_(value,target,direction){if(value==null||!isFinite(Number(value)))return null;const v=Number(value),t=Number(target);if(direction==='LOWER_IS_BETTER'){if(t===0)return v===0?100:0;return Math.min(100,Math.max(0,t/v*100))}if(t<=0)return null;return Math.min(100,Math.max(0,v/t*100))}

function wf2AdminCalculatePerformance_(payload){requireAdmin_(String(payload.adminToken||''));wf2RequireFlag_('PERFORMANCE_ENABLED');const employeeId=String(payload.employeeId||''),employee=employeeRecordV7_(employeeId),startKey=String(payload.startDate||''),endKey=String(payload.endDate||'');if(!employee)throw new Error('ไม่พบพนักงาน');if(!parseIsoDate_(startKey)||!parseIsoDate_(endKey)||endKey<startKey)throw new Error('ช่วงวันที่ไม่ถูกต้อง');const lifecycle=String(employee.employmentStatus||'ACTIVE')==='PROBATION'?'PROBATION':'ACTIVE',raw=wf2PerformanceSources_(employee,startKey,endKey),definitions=wf2ApplicableKpis_(employee,lifecycle),weighted=[];definitions.forEach(def=>{const key=String(def['KPI Key']),metric=raw[key]||{key:key,value:null,dataQualityStatus:'UNSUPPORTED',source:String(def['Source']||''),formula:String(def['Formula']||'')},config=wf2ResolveKpiConfig_(def,employee,lifecycle,startKey,endKey),score=wf2ScoreMetric_(metric.value,config.target,config.direction);metric.target=config.target;metric.weight=config.weight;metric.direction=config.direction;metric.score=score;weighted.push(metric);wf2Append_('Employee_KPI_Results',{'KPI Result ID':wf2EntityId_('KPR'),'Employee ID':employeeId,'KPI Key':key,'Period Start':parseIsoDate_(startKey),'Period End':parseIsoDate_(endKey),'Numerator':metric.numerator==null?'':metric.numerator,'Denominator':metric.denominator==null?'':metric.denominator,'Raw Value':metric.value==null?'':metric.value,'Score':score==null?'':score,'Target':config.target,'Source Reference JSON':jsonCellV7_({source:metric.source,formula:metric.formula,period:{start:startKey,end:endKey}}),'Data Quality Status':metric.dataQualityStatus,'Calculated At':new Date()})});const configured=weighted.filter(x=>Number(x.weight)>0),weights=wf2ValidateWeights_(configured.map(x=>({weight:x.weight,active:true}))),scored=configured.filter(x=>x.value!=null&&x.score!=null);let totalScore=null,configError='';if(configured.length){if(!weights.valid)configError='KPI weights รวม '+weights.total+' ต้องเท่ากับ 100';else if(scored.length!==configured.length)configError='ข้อมูล KPI ที่มีน้ำหนักยังไม่ครบ';else totalScore=Math.round(scored.reduce((sum,x)=>sum+x.score*x.weight/100,0)*100)/100}return{employeeId:employeeId,period:{startDate:startKey,endDate:endKey},lifecycleStage:lifecycle,rawMetrics:weighted,totalScore:totalScore,configError:configError,weightTotal:weights.total,calculatedAt:new Date().toISOString()}}

function wf2AdminSavePerformanceReview_(payload){requireAdmin_(String(payload.adminToken||''));const data=payload.review||{},employee=employeeRecordV7_(String(data.employeeId||''));if(!employee)throw new Error('ไม่พบพนักงาน');const id=String(data.reviewId||'')||wf2EntityId_('REV'),existing=wf2Rows_('Performance_Reviews').find(r=>String(r['Performance Review ID'])===id),record={'Performance Review ID':id,'Employee ID':employee.id,'Reviewer ID':'ADMIN','Review Type':String(data.reviewType||'CUSTOM'),'Period Start':parseIsoDate_(data.periodStart)||'','Period End':parseIsoDate_(data.periodEnd)||'','Criteria JSON':jsonCellV7_(data.criteria||{}),'Numeric Rating':Number(data.numericRating)||0,'Notes':String(data.notes||''),'Status':String(data.status||'DRAFT'),'Submitted At':String(data.status)==='SUBMITTED'?new Date():'','Updated At':new Date()};if(existing)wf2UpdateRow_('Performance_Reviews',existing._row,record);else{record['Created At']=new Date();wf2Append_('Performance_Reviews',record)}return{ok:true,reviewId:id,status:record['Status']}}

function wf2AdminSaveTrainingCatalog_(payload){requireAdmin_(String(payload.adminToken||''));const data=payload.training||{},name=String(data.name||'').trim();if(!name)throw new Error('กรุณาระบุชื่อการอบรม');const id=String(data.trainingId||'')||wf2EntityId_('TRN'),existing=wf2Rows_('Training_Catalog').find(r=>String(r['Training ID'])===id),record={'Training ID':id,'Name':name,'Description':String(data.description||''),'Required Position':String(data.requiredPosition||''),'Validity Days':Math.max(0,Number(data.validityDays)||0),'Active':data.active!==false,'Updated At':new Date()};if(existing)wf2UpdateRow_('Training_Catalog',existing._row,record);else{record['Created At']=new Date();wf2Append_('Training_Catalog',record)}return{ok:true,trainingId:id}}
function wf2AdminAssignTraining_(payload){requireAdmin_(String(payload.adminToken||''));const employee=employeeRecordV7_(String(payload.employeeId||'')),training=wf2Rows_('Training_Catalog').find(r=>String(r['Training ID'])===String(payload.trainingId));if(!employee||!training)throw new Error('ไม่พบพนักงานหรือหลักสูตร');const id=wf2EntityId_('ETR');wf2Append_('Employee_Training',{'Employee Training ID':id,'Employee ID':employee.id,'Training ID':String(training['Training ID']),'Status':'ASSIGNED','Assigned At':new Date(),'Due At':parseIsoDate_(payload.dueAt)||'','Updated At':new Date()});return{ok:true,employeeTrainingId:id}}
function wf2AdminCompleteTraining_(payload){requireAdmin_(String(payload.adminToken||''));const id=String(payload.employeeTrainingId||''),row=wf2Rows_('Employee_Training').find(r=>String(r['Employee Training ID'])===id);if(!row)throw new Error('ไม่พบงานอบรม');const result=String(payload.result||'PASS').toUpperCase(),status=result==='PASS'?'COMPLETED':'FAILED',catalog=wf2Rows_('Training_Catalog').find(r=>String(r['Training ID'])===String(row['Training ID'])),completed=new Date(),expires=status==='COMPLETED'&&catalog&&Number(catalog['Validity Days'])>0?new Date(completed.getTime()+Number(catalog['Validity Days'])*86400000):'';wf2UpdateRow_('Employee_Training',row._row,{'Status':status,'Completed At':completed,'Expires At':expires,'Evidence Document ID':String(payload.evidenceDocumentId||''),'Result':result,'Updated At':completed});return{ok:true,status:status,result:result}}

function wf2AdminRecordIncident_(payload){requireAdmin_(String(payload.adminToken||''));const data=payload.incident||{},employee=employeeRecordV7_(String(data.employeeId||''));if(!employee)throw new Error('ไม่พบพนักงาน');const id=wf2EntityId_('INC');wf2Append_('Employee_Incidents',{'Incident ID':id,'Employee ID':employee.id,'Person ID':wf2EmployeePersonId_(employee.id),'Date':parseIsoDate_(data.date)||new Date(),'Category':String(data.category||''),'Severity':String(data.severity||'MEDIUM'),'Description':String(data.description||''),'Evidence Document ID':String(data.evidenceDocumentId||''),'Reported By':'ADMIN','Reviewed By':String(data.reviewedBy||''),'Action':String(data.action||''),'Status':String(data.status||'OPEN'),'Resolved At':String(data.status)==='RESOLVED'?new Date():'','Created At':new Date(),'Updated At':new Date()});auditLogV7_('ADMIN','ADMIN','RECORD_INCIDENT','EMPLOYEE',employee.id,'',{incidentId:id,severity:String(data.severity||'MEDIUM')},'',String(payload.requestId||''));return{ok:true,incidentId:id}}

function wf2AdminSetCapability_(payload){requireAdmin_(String(payload.adminToken||''));const data=payload.permission||{},employee=employeeRecordV7_(String(data.employeeId||'')),capability=String(data.capability||''),allowed=['canViewApplicants','canScreenApplicants','canInterview','canHire','canManageOnboarding','canVerifyDocuments','canManageSchedule','canViewAttendance','canCorrectAttendance','canApproveLeave','canManageActivity','canReviewActivity','canManageStaffing','canViewPerformance','canReviewPerformance','canViewPayroll','canReviewPayroll','canFinalizePayroll','canManageExit'];if(!employee||allowed.indexOf(capability)<0)throw new Error('พนักงานหรือ capability ไม่ถูกต้อง');const scopeType=String(data.scopeType||'GLOBAL'),scopeId=String(data.scopeId||''),existing=wf2Rows_('User_Permissions').find(r=>String(r['Employee ID'])===employee.id&&String(r['Capability'])===capability&&String(r['Scope Type'])===scopeType&&String(r['Scope ID'])===scopeId),record={'Permission ID':existing?String(existing['Permission ID']):wf2EntityId_('PER'),'Employee ID':employee.id,'Capability':capability,'Scope Type':scopeType,'Scope ID':scopeId,'Allowed':data.allowed!==false,'Active':data.active!==false,'Updated At':new Date(),'Updated By':'ADMIN'};if(existing)wf2UpdateRow_('User_Permissions',existing._row,record);else{record['Created At']=new Date();wf2Append_('User_Permissions',record)}auditLogV7_('ADMIN','ADMIN','SET_CAPABILITY','EMPLOYEE',employee.id,'',record,'',String(payload.requestId||''));return{ok:true,permissionId:record['Permission ID']}}

if(typeof module!=='undefined'&&module.exports){module.exports={scoreMetric:wf2ScoreMetric_}}
