// Workforce V2 operational modules: profile/history, activity, diagnostics and exit.

function wf2EmployeePersonId_(employeeId) {
  return wf2EmployeePersonMap_()[String(employeeId)]||'';
}
function wf2EmployeePersonMap_(){const sh=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(EMPLOYEE_SHEET),out={};if(!sh||sh.getLastRow()<2)return out;const headers=wf2Headers_(sh),idCol=headers.indexOf('Employee ID'),personCol=headers.indexOf('Person ID');if(idCol<0||personCol<0)return out;const rows=sh.getRange(2,1,sh.getLastRow()-1,Math.max(idCol,personCol)+1).getValues();rows.forEach(r=>{if(String(r[idCol]||''))out[String(r[idCol])]=String(r[personCol]||'')});return out}

function wf2AdminEmployeeLifecycleProfile_(payload) {
  requireAdmin_(String(payload.adminToken||''));const employeeId=String(payload.employeeId||''),tab=String(payload.tab||'overview'),employee=employeeRecordV7_(employeeId);if(!employee)throw new Error('ไม่พบพนักงาน');
  const personId=wf2EmployeePersonId_(employeeId),person=personId?wf2Rows_('Persons').find(r=>String(r['Person ID'])===personId):null,base={employee:portalEmployeeSafeV7_(employee),personId:personId,person:person?{'firstName':String(person['First Name']),'lastName':String(person['Last Name']),'nickname':String(person['Nickname']),'phone':String(person['Phone']),'email':String(person['Email']),'lifecycleStage':String(person['Lifecycle Stage'])}:null};
  if(tab==='overview')return Object.assign(base,{summary:{documents:wf2Rows_('Documents').filter(r=>String(r['Employee ID'])===employeeId&&['ACTIVE','VERIFIED'].indexOf(String(r['Status']))>=0).length,openIncidents:wf2Rows_('Employee_Incidents').filter(r=>String(r['Employee ID'])===employeeId&&String(r['Status'])!=='RESOLVED').length,trainingDue:wf2Rows_('Employee_Training').filter(r=>String(r['Employee ID'])===employeeId&&['ASSIGNED','OVERDUE','RENEWAL_DUE'].indexOf(String(r['Status']))>=0).length}});
  const sources={documents:['Documents','Employee ID'],movement:['Employee_Movements','Employee ID'],probation:['Probation_Reviews','Employee ID'],training:['Employee_Training','Employee ID'],incidents:['Employee_Incidents','Employee ID'],performance:['Performance_Reviews','Employee ID'],timeline:['Lifecycle_Events','Employee ID'],exit:['Employee_Exits','Employee ID']},source=sources[tab];if(!source)throw new Error('Profile tab ไม่ถูกต้อง');
  const rows=wf2Rows_(source[0]).filter(r=>String(r[source[1]])===employeeId).reverse().slice(0,200).map(wf2ClientRow_);return Object.assign(base,{tab:tab,rows:rows});
}

function wf2ClientRow_(row){const out={};Object.keys(row).forEach(k=>{if(k==='_row')return;const v=row[k];out[k]=v instanceof Date?formatDateTimeForClient_(v):v});return out}

function wf2AdminSearchEmployees_(payload){requireAdmin_(String(payload.adminToken||''));const query=String(payload.query||'').trim().toLowerCase(),limit=Math.min(100,Math.max(1,Number(payload.limit)||30));let rows=getEmployeesAdmin_().filter(e=>!query||(e.id+' '+e.name+' '+e.nickname).toLowerCase().indexOf(query)>=0);return{rows:rows.slice(0,limit).map(e=>({employeeId:e.id,name:e.name,nickname:e.nickname,branchCode:e.branch,departmentCode:e.department,positionCode:e.position,employmentStatus:e.employmentStatus,active:e.active})),total:rows.length}}

function wf2AdminGetInterviews_(payload){requireAdmin_(String(payload.adminToken||''));const persons={};wf2Rows_('Persons').forEach(p=>persons[String(p['Person ID'])]=p);let rows=wf2Rows_('Applicant_Interviews').reverse();if(payload.status)rows=rows.filter(r=>String(r['Status'])===String(payload.status));return{rows:rows.slice(0,200).map(r=>{const p=persons[String(r['Person ID'])]||{};return{interviewId:String(r['Interview ID']),applicantId:String(r['Applicant ID']),personId:String(r['Person ID']),name:(String(p['First Name']||'')+' '+String(p['Last Name']||'')).trim(),nickname:String(p['Nickname']||''),date:formatDateInputForClient_(r['Interview Date']),time:String(r['Interview Time']||''),branchCode:String(r['Branch Code']||''),location:String(r['Location']||''),interviewerId:String(r['Interviewer ID']||''),positionCode:String(r['Position Code']||''),status:String(r['Status']||''),result:String(r['Result']||'')}})}}

function wf2AdminRecordEmployeeMovement_(payload) {
  requireAdmin_(String(payload.adminToken||''));const data=payload.movement||{},employeeId=String(data.employeeId||''),employee=employeeRecordV7_(employeeId);if(!employee)throw new Error('ไม่พบพนักงาน');
  const fields={BRANCH:{header:'Branch',prop:'branch',type:'BRANCH_TRANSFER'},DEPARTMENT:{header:'Department',prop:'department',type:'DEPARTMENT_TRANSFER'},POSITION:{header:'Position',prop:'position',type:'POSITION_CHANGE'},WAGE_AMOUNT:{header:'Wage Amount',prop:'wageAmount',type:'WAGE_CHANGE'},WAGE_TYPE:{header:'Wage Type',prop:'wageType',type:'WAGE_CHANGE'},ACCESS_ROLE:{header:'Access Role',prop:'accessRole',type:'ROLE_CHANGE'},EMPLOYMENT_STATUS:{header:'Employment Status',prop:'employmentStatus',type:'EMPLOYMENT_TYPE_CHANGE'}},key=String(data.fieldName||'').toUpperCase(),def=fields[key];if(!def)throw new Error('ประเภทการเปลี่ยนแปลงไม่ถูกต้อง');
  let next=data.newValue;if(key==='BRANCH')next=validateBranchV7_(next,false);if(key==='DEPARTMENT')next=validateDepartmentV7_(next,false);if(key==='ACCESS_ROLE')next=validateAccessRoleV7_(next);if(key==='WAGE_AMOUNT'){next=Number(next);if(!isFinite(next)||next<0)throw new Error('ค่าแรงไม่ถูกต้อง')}
  const effective=parseIsoDate_(data.effectiveDate);if(!effective)throw new Error('วันที่มีผลไม่ถูกต้อง');const today=attendanceDateKey_(new Date()),effectiveKey=attendanceDateKey_(effective),status=effectiveKey<=today?'APPLIED':'SCHEDULED',id=wf2EntityId_('MOV'),personId=wf2EmployeePersonId_(employeeId),record={'Movement ID':id,'Employee ID':employeeId,'Person ID':personId,'Movement Type':String(data.movementType||def.type),'Effective Date':effective,'Field Name':key,'Old Value':String(employee[def.prop]==null?'':employee[def.prop]),'New Value':String(next),'Reason':String(data.reason||''),'Approved By':'ADMIN','Status':status,'Applied At':status==='APPLIED'?new Date():'','Created At':new Date()};
  wf2Append_('Employee_Movements',record);if(status==='APPLIED')wf2ApplyEmployeeField_(employeeId,def.header,next);
  wf2AddEvent_(personId,employeeId,'EMPLOYEE_MOVEMENT',id,record['Movement Type'],key+': '+record['Old Value']+' → '+record['New Value'],{effectiveDate:effectiveKey,reason:record['Reason']},'ADMIN');auditLogV7_('ADMIN','ADMIN','RECORD_EMPLOYEE_MOVEMENT','EMPLOYEE',employeeId,{field:key,value:record['Old Value']},{field:key,value:record['New Value'],effectiveDate:effectiveKey},record['Reason'],String(payload.requestId||''));return{ok:true,movementId:id,status:status};
}

function wf2ApplyEmployeeField_(employeeId,header,value){const sh=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(EMPLOYEE_SHEET),headers=wf2Headers_(sh),idCol=headers.indexOf('Employee ID'),target=headers.indexOf(header);if(idCol<0||target<0)throw new Error('Employee schema ไม่มี '+header);const ids=sh.getRange(2,idCol+1,Math.max(0,sh.getLastRow()-1),1).getValues();for(let i=0;i<ids.length;i++)if(String(ids[i][0])===String(employeeId)){sh.getRange(i+2,target+1).setValue(value);invalidateAdminSummary_();return}throw new Error('ไม่พบพนักงาน')}

function wf2AdminApplyDueMovements_(payload){requireAdmin_(String(payload.adminToken||''));const today=attendanceDateKey_(new Date()),rows=wf2Rows_('Employee_Movements').filter(r=>String(r['Status'])==='SCHEDULED'&&attendanceDateKey_(r['Effective Date'])<=today),fields={BRANCH:'Branch',DEPARTMENT:'Department',POSITION:'Position',WAGE_AMOUNT:'Wage Amount',WAGE_TYPE:'Wage Type',ACCESS_ROLE:'Access Role',EMPLOYMENT_STATUS:'Employment Status'};rows.forEach(r=>{wf2ApplyEmployeeField_(String(r['Employee ID']),fields[String(r['Field Name'])],String(r['New Value']));wf2UpdateRow_('Employee_Movements',r._row,{'Status':'APPLIED','Applied At':new Date()})});return{ok:true,applied:rows.length}}

function wf2AdminSaveProbationReview_(payload){requireAdmin_(String(payload.adminToken||''));const data=payload.review||{},employeeId=String(data.employeeId||''),employee=employeeRecordV7_(employeeId);if(!employee)throw new Error('ไม่พบพนักงาน');const status=String(data.status||'IN_PROGRESS'),allowed=['IN_PROGRESS','PASS','EXTEND','NOT_PASS'];if(allowed.indexOf(status)<0)throw new Error('ผล Probation ไม่ถูกต้อง');const id=String(data.probationReviewId||'')||wf2EntityId_('PRB'),existing=wf2Rows_('Probation_Reviews').find(r=>String(r['Probation Review ID'])===id),record={'Probation Review ID':id,'Employee ID':employeeId,'Person ID':wf2EmployeePersonId_(employeeId),'Start Date':parseIsoDate_(data.startDate)||employee.startDate,'Planned End Date':parseIsoDate_(data.plannedEndDate)||'','Actual End Date':parseIsoDate_(data.actualEndDate)||'','Status':status,'Review Date':new Date(),'Reviewer ID':'ADMIN','KPI Result JSON':jsonCellV7_(data.kpiResults||{}),'Supervisor Rating':Number(data.supervisorRating)||0,'Notes':String(data.notes||''),'Updated At':new Date()};if(existing)wf2UpdateRow_('Probation_Reviews',existing._row,record);else{record['Created At']=new Date();wf2Append_('Probation_Reviews',record)}if(status==='PASS')wf2ApplyEmployeeField_(employeeId,'Employment Status','ACTIVE');if(status==='NOT_PASS')wf2AddWorkItem_('PROBATION_NOT_PASS',id,'ดำเนินการผลทดลองงานไม่ผ่าน '+employee.name,'ADMIN','',new Date(),'URGENT',employee.branch,employee.department);wf2AddEvent_(record['Person ID'],employeeId,'PROBATION_REVIEW',id,'PROBATION_'+status,'ผลทดลองงาน '+status,{supervisorRating:record['Supervisor Rating']},'ADMIN');return{ok:true,probationReviewId:id,status:status}}

function wf2GetOrCreateActivityReport_(employee,dateKey){const existing=wf2Rows_('Activity_Reports').find(r=>String(r['Employee ID'])===employee.id&&attendanceDateKey_(r['Date'])===dateKey);if(existing)return existing;const schedule=latestPublishedScheduleItemV7_(employee.id,dateKey);if(!schedule)throw new Error('ไม่พบตารางงานที่ประกาศสำหรับวันนี้');const templates=wf2Rows_('Activity_Templates').filter(t=>t['Active']!==false&&(!String(t['Branch Code'])||String(t['Branch Code'])===schedule.branchCode)&&(!String(t['Department Code'])||String(t['Department Code'])===employee.department)&&(!String(t['Position Code'])||String(t['Position Code'])===employee.position)&&(!String(t['Shift Code'])||String(t['Shift Code'])===schedule.shiftCode));const reportId=wf2EntityId_('ACT'),now=new Date();wf2Append_('Activity_Reports',{'Activity Report ID':reportId,'Employee ID':employee.id,'Date':parseIsoDate_(dateKey),'Branch Code':schedule.branchCode,'Department Code':employee.department,'Position Code':employee.position,'Shift Code':schedule.shiftCode,'Status':'NOT_STARTED','Created At':now,'Updated At':now});templates.forEach(t=>{let due='';if(String(t['Due Offset Minutes'])!==''){const window=shiftWindowV7_(dateKey,schedule.shiftCode);due=new Date(window.start.getTime()+Number(t['Due Offset Minutes'])*60000)}wf2Append_('Activity_Items',{'Activity Item ID':wf2EntityId_('ATI'),'Report ID':reportId,'Template ID':String(t['Activity Template ID']),'Category ID':String(t['Category ID']),'Task':String(t['Task']),'Target':t['Target'],'Unit':String(t['Unit']),'Status':'NOT_STARTED','Due At':due,'Issue Flag':false,'Created At':now,'Updated At':now})});return wf2Rows_('Activity_Reports').find(r=>String(r['Activity Report ID'])===reportId)}

function wf2PortalGetDailyActivities_(payload){wf2RequireFlag_('ACTIVITY_ENABLED');const employee=requirePortalV7_(payload.portalToken),dateKey=String(payload.date||Utilities.formatDate(new Date(),TZ,'yyyy-MM-dd')),report=wf2GetOrCreateActivityReport_(employee,dateKey),items=wf2Rows_('Activity_Items').filter(r=>String(r['Report ID'])===String(report['Activity Report ID'])).map(wf2ClientRow_);return{report:wf2ClientRow_(report),items:items,serverEpochMs:Date.now()}}

function wf2PortalAddActivityItem_(payload){wf2RequireFlag_('ACTIVITY_ENABLED');const employee=requirePortalV7_(payload.portalToken),reportId=String(payload.activityReportId||''),report=wf2Rows_('Activity_Reports').find(r=>String(r['Activity Report ID'])===reportId&&String(r['Employee ID'])===employee.id);if(!report)throw new Error('ไม่พบรายงาน');if(/^SUBMITTED/.test(String(report['Status'])))throw new Error('รายงานถูกส่งแล้ว');const task=String(payload.task||'').trim();if(!task)throw new Error('กรุณาระบุงานเพิ่มเติม');const id=wf2EntityId_('ATI');wf2Append_('Activity_Items',{'Activity Item ID':id,'Report ID':reportId,'Task':task,'Target':payload.target||'','Unit':String(payload.unit||''),'Status':'NOT_STARTED','Issue Flag':false,'Note':String(payload.note||''),'Created At':new Date(),'Updated At':new Date()});return{ok:true,activityItemId:id}}

function wf2PortalUpdateActivityItem_(payload){wf2RequireFlag_('ACTIVITY_ENABLED');const employee=requirePortalV7_(payload.portalToken),id=String(payload.activityItemId||''),item=wf2Rows_('Activity_Items').find(r=>String(r['Activity Item ID'])===id);if(!item)throw new Error('ไม่พบงาน');const report=wf2Rows_('Activity_Reports').find(r=>String(r['Activity Report ID'])===String(item['Report ID'])&&String(r['Employee ID'])===employee.id);if(!report)throw new Error('ไม่มีสิทธิ์แก้ไขงานนี้');const status=String(payload.status||''),allowed=['NOT_STARTED','IN_PROGRESS','DONE','ISSUE'];if(allowed.indexOf(status)<0)throw new Error('สถานะงานไม่ถูกต้อง');const now=new Date(),changes={'Status':status,'Actual':payload.actual==null?item['Actual']:payload.actual,'Note':String(payload.note||''),'Issue Flag':status==='ISSUE','Updated At':now};if(status==='IN_PROGRESS'&&!item['Started At'])changes['Started At']=now;if(status==='DONE'||status==='ISSUE')changes['Completed At']=now;wf2UpdateRow_('Activity_Items',item._row,changes);wf2UpdateRow_('Activity_Reports',report._row,{'Status':'IN_PROGRESS','Updated At':now});if(status==='ISSUE')wf2CreateActivityIssue_(employee,item,String(payload.note||''),String(payload.severity||'MEDIUM'));return{ok:true,activityItemId:id,status:status}}

function wf2CreateActivityIssue_(employee,item,description,severity){const existing=wf2Rows_('Activity_Issues').find(r=>String(r['Activity Item ID'])===String(item['Activity Item ID'])&&String(r['Status'])!=='RESOLVED');if(existing)return existing;const id=wf2EntityId_('ISS');wf2Append_('Activity_Issues',{'Activity Issue ID':id,'Activity Item ID':String(item['Activity Item ID']),'Employee ID':employee.id,'Description':description,'Severity':severity,'Created At':new Date(),'Status':'OPEN','Updated At':new Date()});wf2AddWorkItem_('ACTIVITY_ISSUE',id,'Activity issue: '+String(item['Task']),'MANAGER','',new Date(Date.now()+4*60*60*1000),severity==='HIGH'?'URGENT':'NORMAL',employee.branch,employee.department);return{id:id}}

function wf2PortalSubmitActivityReport_(payload){wf2RequireFlag_('ACTIVITY_ENABLED');const employee=requirePortalV7_(payload.portalToken),id=String(payload.activityReportId||''),report=wf2Rows_('Activity_Reports').find(r=>String(r['Activity Report ID'])===id&&String(r['Employee ID'])===employee.id);if(!report)throw new Error('ไม่พบรายงาน');const items=wf2Rows_('Activity_Items').filter(r=>String(r['Report ID'])===id);if(!items.length)throw new Error('รายงานไม่มีรายการงาน');const pending=items.filter(r=>['DONE','ISSUE'].indexOf(String(r['Status']))<0).length,status=pending?'SUBMITTED_WITH_PENDING':'SUBMITTED';wf2UpdateRow_('Activity_Reports',report._row,{'Status':status,'Submitted At':new Date(),'Updated At':new Date()});return{ok:true,status:status,assigned:items.length,completed:items.filter(r=>String(r['Status'])==='DONE').length,issues:items.filter(r=>String(r['Status'])==='ISSUE').length,pending:pending}}

function wf2RequireActivityManager_(payload){const employee=requirePortalV7_(payload.portalToken,['SUPERVISOR','MANAGER','ADMIN']),branch=validateBranchV7_(payload.branchCode,false),department=validateDepartmentV7_(payload.departmentCode,false);wf2RequireCapability_(employee,'canManageActivity',branch,department);return{employee:employee,branch:branch,department:department}}
function wf2RequireCapability_(employee,capability,branch,department){const permitted=wf2Rows_('User_Permissions').some(r=>String(r['Employee ID'])===employee.id&&String(r['Capability'])===capability&&r['Allowed']!==false&&r['Active']!==false&&(['GLOBAL','BRANCH','DEPARTMENT'].indexOf(String(r['Scope Type']))>=0)&&((String(r['Scope Type'])==='GLOBAL')||(String(r['Scope Type'])==='BRANCH'&&String(r['Scope ID'])===branch)||(String(r['Scope Type'])==='DEPARTMENT'&&String(r['Scope ID'])===department)));if(!permitted)throw new Error('ไม่มี capability: '+capability)}
function wf2ManagerGetActivityIssues_(payload){wf2RequireFlag_('ACTIVITY_ENABLED');const auth=wf2RequireActivityManager_(payload),team=new Set(getEmployeesAdmin_().filter(e=>e.branch===auth.branch&&e.department===auth.department).map(e=>e.id)),rows=wf2Rows_('Activity_Issues').filter(r=>team.has(String(r['Employee ID']))&&(!payload.status||String(r['Status'])===String(payload.status))).reverse().slice(0,200).map(wf2ClientRow_);return{rows:rows}}
function wf2ManagerResolveActivityIssue_(payload){wf2RequireFlag_('ACTIVITY_ENABLED');const auth=wf2RequireActivityManager_(payload),id=String(payload.activityIssueId||''),issue=wf2Rows_('Activity_Issues').find(r=>String(r['Activity Issue ID'])===id),employee=issue&&employeeRecordV7_(String(issue['Employee ID']));if(!issue||!employee||employee.branch!==auth.branch||employee.department!==auth.department)throw new Error('ไม่พบปัญหาในขอบเขตที่รับผิดชอบ');wf2UpdateRow_('Activity_Issues',issue._row,{'Assigned To':auth.employee.id,'Action':String(payload.action||''),'Status':'RESOLVED','Resolved At':new Date(),'Updated At':new Date()});return{ok:true,status:'RESOLVED'}}

function wf2AdminGetActivityTemplates_(payload){requireAdmin_(String(payload.adminToken||''));let rows=wf2Rows_('Activity_Templates');if(payload.departmentCode)rows=rows.filter(r=>String(r['Department Code'])===String(payload.departmentCode));if(payload.positionCode)rows=rows.filter(r=>String(r['Position Code'])===String(payload.positionCode));return{rows:rows.map(wf2ClientRow_)}}
function wf2AdminSaveActivityTemplate_(payload){requireAdmin_(String(payload.adminToken||''));const data=payload.template||{},task=String(data.task||'').trim();if(!task)throw new Error('กรุณาระบุชื่องาน');const id=String(data.activityTemplateId||'')||wf2EntityId_('TPL'),existing=wf2Rows_('Activity_Templates').find(r=>String(r['Activity Template ID'])===id),record={'Activity Template ID':id,'Category ID':String(data.categoryId||''),'Branch Code':data.branchCode?validateBranchV7_(data.branchCode,false):'','Department Code':data.departmentCode?validateDepartmentV7_(data.departmentCode,false):'','Position Code':String(data.positionCode||''),'Shift Code':data.shiftCode?validateShiftV7_(data.shiftCode,false):'','Task':task,'Target':data.target||'','Unit':String(data.unit||''),'Due Offset Minutes':data.dueOffsetMinutes===''?'':Number(data.dueOffsetMinutes)||0,'Required':data.required!==false,'Active':data.active!==false,'Updated At':new Date()};if(existing)wf2UpdateRow_('Activity_Templates',existing._row,record);else{record['Created At']=new Date();wf2Append_('Activity_Templates',record)}return{ok:true,activityTemplateId:id}}
function wf2AdminActivityDashboard_(payload){requireAdmin_(String(payload.adminToken||''));const start=String(payload.startDate||''),end=String(payload.endDate||''),branch=String(payload.branchCode||''),department=String(payload.departmentCode||''),reports=wf2Rows_('Activity_Reports').filter(r=>(!start||attendanceDateKey_(r['Date'])>=start)&&(!end||attendanceDateKey_(r['Date'])<=end)&&(!branch||String(r['Branch Code'])===branch)&&(!department||String(r['Department Code'])===department)),ids=new Set(reports.map(r=>String(r['Activity Report ID']))),items=wf2Rows_('Activity_Items').filter(r=>ids.has(String(r['Report ID']))),submitted=reports.filter(r=>/^SUBMITTED/.test(String(r['Status']))).length,done=items.filter(r=>String(r['Status'])==='DONE').length,issues=items.filter(r=>String(r['Status'])==='ISSUE').length,onTime=items.filter(r=>String(r['Status'])==='DONE'&&(!r['Due At']||new Date(r['Completed At'])<=new Date(r['Due At']))).length;return{requiredReporters:reports.length,submitted:submitted,notSubmitted:reports.length-submitted,assignedTasks:items.length,completed:done,pending:items.length-done-issues,issues:issues,submissionRate:wf2Ratio_(submitted,reports.length),completionRate:wf2Ratio_(done,items.length),onTimeCompletionRate:wf2Ratio_(onTime,done),formulas:{submissionRate:'submitted Activity_Reports / required Activity_Reports',completionRate:'DONE Activity_Items / assigned Activity_Items',onTimeCompletionRate:'DONE by dueAt / DONE Activity_Items'},serverEpochMs:Date.now()}}

function wf2AdminCompleteWorkItem_(payload){requireAdmin_(String(payload.adminToken||''));const id=String(payload.workItemId||''),item=wf2Rows_('Work_Queue').find(r=>String(r['Work Item ID'])===id);if(!item)throw new Error('ไม่พบงาน');wf2UpdateRow_('Work_Queue',item._row,{'Status':'DONE','Updated At':new Date(),'Completed At':new Date()});return{ok:true,workItemId:id}}

function wf2AdminCreateEmployeeExit_(payload){requireAdmin_(String(payload.adminToken||''));wf2RequireFlag_('OFFBOARDING_ENABLED');const data=payload.exit||{},employeeId=String(data.employeeId||''),employee=employeeRecordV7_(employeeId);if(!employee)throw new Error('ไม่พบพนักงาน');if(wf2Rows_('Employee_Exits').some(r=>String(r['Employee ID'])===employeeId&&['EXITED','CANCELLED'].indexOf(String(r['Status']))<0))throw new Error('มี Exit workflow ที่ยังไม่จบ');const id=wf2EntityId_('EXT'),personId=wf2EmployeePersonId_(employeeId),record={'Exit ID':id,'Employee ID':employeeId,'Person ID':personId,'Exit Type':String(data.exitType||'RESIGNATION'),'Reason Category':String(data.reasonCategory||''),'Reason Detail':String(data.reasonDetail||''),'Notice Date':parseIsoDate_(data.noticeDate)||new Date(),'Last Working Date':parseIsoDate_(data.lastWorkingDate)||'','Notice Days':Number(data.noticeDays)||0,'Status':'NOTICE_PERIOD','Approved By':'ADMIN','Handover Status':'PENDING','Asset Return Status':'PENDING','Document Status':'PENDING','Final Payroll Status':'PENDING','Exit Interview Status':'PENDING','Access Closed Status':'PENDING','Rehire Eligible':data.rehireEligible!==false,'Created At':new Date(),'Updated At':new Date()};wf2Append_('Employee_Exits',record);[['HANDOVER','ส่งมอบงาน','MANAGER'],['SCHEDULE','ปิดตารางงาน','MANAGER'],['ATTENDANCE','ตรวจเวลาให้ครบ','ADMIN'],['FINAL_PAYROLL','สรุปค่าแรงงวดสุดท้าย','ADMIN'],['ASSET_RETURN','คืนทรัพย์สิน','MANAGER'],['DOCUMENTS','ตรวจเอกสาร','ADMIN'],['ACCESS_CLOSE','ปิดสิทธิ์เมื่อออกจริง','ADMIN'],['EXIT_INTERVIEW','Exit Interview','ADMIN']].forEach(task=>wf2Append_('Exit_Checklist',{'Exit Checklist ID':wf2EntityId_('EXC'),'Exit ID':id,'Task Key':task[0],'Task Label':task[1],'Owner Role':task[2],'Status':'PENDING','Created At':new Date(),'Updated At':new Date()}));wf2AddEvent_(personId,employeeId,'EMPLOYEE_EXIT',id,'NOTICE_PERIOD','เริ่มกระบวนการออกจากองค์กร',{lastWorkingDate:formatDateInputForClient_(record['Last Working Date'])},'ADMIN');return{ok:true,exitId:id,status:'NOTICE_PERIOD'}}

function wf2AdminUpdateExitChecklist_(payload){requireAdmin_(String(payload.adminToken||''));const id=String(payload.exitChecklistId||''),row=wf2Rows_('Exit_Checklist').find(r=>String(r['Exit Checklist ID'])===id);if(!row)throw new Error('ไม่พบ Checklist');const status=String(payload.status||'DONE');if(['PENDING','IN_PROGRESS','DONE','BLOCKED'].indexOf(status)<0)throw new Error('สถานะไม่ถูกต้อง');wf2UpdateRow_('Exit_Checklist',row._row,{'Status':status,'Completed At':status==='DONE'?new Date():'','Completed By':'ADMIN','Note':String(payload.note||''),'Updated At':new Date()});return{ok:true,status:status}}

function wf2AdminCompleteEmployeeExit_(payload){requireAdmin_(String(payload.adminToken||''));const id=String(payload.exitId||''),exit=wf2Rows_('Employee_Exits').find(r=>String(r['Exit ID'])===id);if(!exit)throw new Error('ไม่พบ Exit workflow');const tasks=wf2Rows_('Exit_Checklist').filter(r=>String(r['Exit ID'])===id),pending=tasks.filter(r=>String(r['Status'])!=='DONE');if(pending.length)throw new Error('Checklist ยังไม่ครบ '+pending.length+' รายการ');const employeeId=String(exit['Employee ID']),lastDate=exit['Last Working Date'];wf2UpdateRow_('Employee_Exits',exit._row,{'Status':'EXITED','Handover Status':'DONE','Asset Return Status':'DONE','Document Status':'DONE','Final Payroll Status':'DONE','Exit Interview Status':'DONE','Access Closed Status':'DONE','Completed At':new Date(),'Updated At':new Date()});wf2ApplyEmployeeField_(employeeId,'Employment Status','EXITED');wf2ApplyEmployeeField_(employeeId,'Active',false);if(lastDate)wf2ApplyEmployeeField_(employeeId,'Resignation Date',lastDate);const personId=String(exit['Person ID']);if(personId){const person=wf2Rows_('Persons').find(r=>String(r['Person ID'])===personId);if(person)wf2UpdateRow_('Persons',person._row,{'Lifecycle Stage':exit['Rehire Eligible']===false?'EXITED':'REHIRE_POOL','Updated At':new Date()})}wf2AddEvent_(personId,employeeId,'EMPLOYEE_EXIT',id,'EXITED','สิ้นสุดการจ้างงาน',{},'ADMIN');return{ok:true,status:'EXITED'}}

function wf2AdminDiagnostics_(payload){requireAdmin_(String(payload.adminToken||''));const persons=wf2Rows_('Persons'),employees=getEmployeesAdmin_(),personByEmployee=wf2EmployeePersonMap_(),documents=wf2Rows_('Documents'),applicants=wf2Rows_('Applicants'),branches=new Set(getBranchesV7_(true).map(x=>x.code)),departments=new Set(getDepartmentsV7_(true).map(x=>x.code)),positions=new Set(wf2ActivePositions_().map(x=>x.code)),employeeIds=new Set(employees.map(e=>e.id)),personIds=new Set(persons.map(p=>String(p['Person ID']))),issues=[];const duplicateGroups={};persons.forEach(p=>{const keys=[String(p['Phone Normalized']||''),String(p['Email Normalized']||'').toLowerCase()].filter(Boolean);keys.forEach(k=>(duplicateGroups[k]||(duplicateGroups[k]=[])).push(String(p['Person ID'])))});Object.keys(duplicateGroups).forEach(k=>{if(duplicateGroups[k].length>1)issues.push({type:'DUPLICATE_PERSON_CANDIDATE',key:k,entities:duplicateGroups[k]})});employees.forEach(e=>{const personId=personByEmployee[e.id]||'';if(!personId||!personIds.has(personId))issues.push({type:'ORPHAN_EMPLOYEE',entityId:e.id});if(e.branch&&!branches.has(e.branch))issues.push({type:'INVALID_BRANCH',entityId:e.id,value:e.branch});if(e.department&&!departments.has(e.department))issues.push({type:'INVALID_DEPARTMENT',entityId:e.id,value:e.department});if(!e.position||!positions.has(e.position))issues.push({type:'INVALID_POSITION',entityId:e.id,value:e.position})});documents.forEach(d=>{if(String(d['Employee ID'])&&!employeeIds.has(String(d['Employee ID'])))issues.push({type:'ORPHAN_DOCUMENT',entityId:String(d['Document ID'])})});applicants.forEach(a=>{if(!personIds.has(String(a['Person ID'])))issues.push({type:'APPLICANT_WITHOUT_PERSON',entityId:String(a['Applicant ID'])});if(!branches.has(String(a['Branch Code'])))issues.push({type:'INVALID_BRANCH',entityId:String(a['Applicant ID']),value:String(a['Branch Code'])})});const counts={};issues.forEach(x=>counts[x.type]=(counts[x.type]||0)+1);return{ok:issues.length===0,counts:counts,issues:issues.slice(0,500),checkedAt:new Date().toISOString()}}
