// Attendance control view. Schedule, Attendance and Leave remain separate sources of truth.

function wf2AdminAttendanceControl_(payload){
  requireAdmin_(String(payload.adminToken||''));
  const dateKey=String(payload.date||Utilities.formatDate(new Date(),TZ,'yyyy-MM-dd'));if(!parseIsoDate_(dateKey))throw new Error('วันที่ไม่ถูกต้อง');
  const branch=String(payload.branchCode||''),department=String(payload.departmentCode||''),employeeQuery=String(payload.employeeQuery||'').trim().toLowerCase(),statusFilter=String(payload.status||''),ss=SpreadsheetApp.openById(SPREADSHEET_ID),employees=getEmployeesAdmin_(),employeeMap={};employees.forEach(e=>employeeMap[e.id]=e);
  const published=new Set(scheduleVersionRowsV7_().filter(v=>v.status==='PUBLISHED').map(v=>v.versionId)),scheduleSh=ss.getSheetByName(WORK_SCHEDULES_SHEET),scheduled={};
  if(scheduleSh&&scheduleSh.getLastRow()>=2)scheduleSh.getRange(2,1,scheduleSh.getLastRow()-1,17).getValues().forEach(r=>{if(!published.has(String(r[1]))||attendanceDateKey_(r[3])!==dateKey)return;const workStatus=String(r[9]||'WORK').toUpperCase();if(['OFF','LEAVE','WEEKLY_OFF'].indexOf(workStatus)>=0)return;const id=String(r[4]||'');if(!id)return;scheduled[id]={employeeId:id,employeeName:String(r[5]||''),branchCode:String(r[6]||''),departmentCode:String(r[7]||''),shiftCode:String(r[8]||''),startTime:String(r[10]||''),endTime:String(r[11]||'')}});
  const eventMap={},att=ss.getSheetByName(ATTENDANCE_SHEET),attLast=att?att.getLastRow():0;if(att&&attLast>=2)att.getRange(2,1,attLast-1,Math.min(19,att.getLastColumn())).getValues().forEach(r=>{const timestamp=r[1] instanceof Date?r[1]:null,id=String(r[4]||''),rowDate=attendanceDateKey_(r[2])||(timestamp?Utilities.formatDate(timestamp,TZ,'yyyy-MM-dd'):'');if(!timestamp||!id||rowDate!==dateKey||String(r[11]||'').indexOf('VOID')===0)return;(eventMap[id]||(eventMap[id]=[])).push({timestamp:timestamp,action:String(r[6]||''),kind:actionKindServer_(r[6]),status:String(r[11]||'')})});Object.keys(eventMap).forEach(id=>eventMap[id].sort((a,b)=>a.timestamp-b.timestamp));
  const leaveIds=new Set(),leave=ss.getSheetByName(LEAVE_SHEET),leaveLast=leave?leave.getLastRow():0;if(leave&&leaveLast>=2)leave.getRange(2,1,leaveLast-1,Math.min(14,leave.getLastColumn())).getValues().forEach(r=>{if(String(r[2])!=='APPROVED')return;const start=attendanceDateKey_(r[7]),end=attendanceDateKey_(r[8]);if(start&&end&&dateKey>=start&&dateKey<=end)leaveIds.add(String(r[3]||''))});
  const ids=new Set(Object.keys(scheduled).concat(Object.keys(eventMap)).concat(Array.from(leaveIds))),now=new Date(),rows=[];
  ids.forEach(id=>{const employee=employeeMap[id]||{},schedule=scheduled[id]||null,events=eventMap[id]||[],ins=events.filter(e=>e.kind==='IN'),outs=events.filter(e=>e.kind==='OUT'),firstIn=ins[0]&&ins[0].timestamp,lastOut=outs.length&&outs[outs.length-1].timestamp,actualBranch=String(employee.branch||schedule&&schedule.branchCode||''),actualDepartment=String(employee.department||schedule&&schedule.departmentCode||'');if(branch&&actualBranch!==branch)return;if(department&&actualDepartment!==department)return;const haystack=(id+' '+String(employee.name||schedule&&schedule.employeeName||'')+' '+String(employee.nickname||'')).toLowerCase();if(employeeQuery&&haystack.indexOf(employeeQuery)<0)return;let shiftWindow=null;try{if(schedule)shiftWindow=shiftWindowV7_(dateKey,schedule.shiftCode)}catch(e){}let status='NORMAL',lateMinutes=0;if(leaveIds.has(id))status='LEAVE';else if(!schedule&&events.length)status='UNPLANNED';else if(schedule&&!firstIn)status=shiftWindow&&now>shiftWindow.end?'ABSENT':'NOT_CHECKED_IN';else if(schedule&&firstIn){const grace=shiftWindow?(Number(shiftWindow.shift.lateGraceMinutes)||0):0;if(shiftWindow&&firstIn.getTime()>shiftWindow.start.getTime()+grace*60000){status='LATE';lateMinutes=Math.max(0,Math.floor((firstIn.getTime()-shiftWindow.start.getTime())/60000))}if(!lastOut&&shiftWindow&&now>shiftWindow.end)status='NO_CHECK_OUT'}const workedMinutes=firstIn&&lastOut&&lastOut>firstIn?Math.floor((lastOut-firstIn)/60000):0,standardMinutes=shiftWindow?(Number(shiftWindow.shift.standardHours)||0)*60:0,otMinutes=Math.max(0,workedMinutes-standardMinutes);rows.push({employeeId:id,employeeName:String(employee.name||schedule&&schedule.employeeName||''),nickname:String(employee.nickname||''),branchCode:actualBranch,departmentCode:actualDepartment,shiftCode:schedule?String(schedule.shiftCode):'',scheduledShift:schedule?String(schedule.startTime||'')+'–'+String(schedule.endTime||''):'-',checkIn:firstIn?Utilities.formatDate(firstIn,TZ,'HH:mm'):'',checkOut:lastOut?Utilities.formatDate(lastOut,TZ,'HH:mm'):'',workedHours:Math.round(workedMinutes/6)/10,lateMinutes:lateMinutes,otHours:Math.round(otMinutes/6)/10,status:status})});
  rows.sort((a,b)=>{const priority={ABSENT:0,NO_CHECK_OUT:1,NOT_CHECKED_IN:2,LATE:3,UNPLANNED:4,LEAVE:5,NORMAL:6};return(priority[a.status]??9)-(priority[b.status]??9)||a.employeeName.localeCompare(b.employeeName,'th')});
  const summary={expected:Object.keys(scheduled).length,present:rows.filter(r=>r.checkIn).length,notCheckedIn:rows.filter(r=>r.status==='NOT_CHECKED_IN').length,leave:rows.filter(r=>r.status==='LEAVE').length,absent:rows.filter(r=>r.status==='ABSENT').length,late:rows.filter(r=>r.status==='LATE').length,noCheckOut:rows.filter(r=>r.status==='NO_CHECK_OUT').length,unplanned:rows.filter(r=>r.status==='UNPLANNED').length,ot:Math.round(rows.reduce((s,r)=>s+r.otHours,0)*10)/10};
  const filtered=statusFilter?rows.filter(r=>r.status===statusFilter):rows;
  return{date:dateKey,summary:summary,rows:filtered.slice(0,500),total:filtered.length,sources:{expected:'Work_Schedules + PUBLISHED Schedule_Versions',actual:'Attendance',leave:'Leave_Requests APPROVED'},serverEpochMs:Date.now()};
}
